# Generated by Django 5.1 on 2025-03-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=10, unique=True)),
                ('hod_id', models.CharField(max_length=12)),
                ('event_name', models.CharField(max_length=255)),
                ('event_details', models.TextField()),
                ('event_venue', models.CharField(max_length=255)),
                ('event_date_range', models.CharField(max_length=255)),
                ('event_images', models.JSONField()),
                ('digital_pass', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('event_id', models.CharField(max_length=10)),
                ('event_date_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('number_of_tickets', models.IntegerField()),
            ],
        ),
    ]
