# Generated by Django 5.1 on 2025-03-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date_id', models.CharField(max_length=10)),
                ('reseller_id', models.CharField(max_length=10)),
                ('assigned_tickets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date_id', models.CharField(max_length=10)),
                ('seller_id', models.CharField(max_length=10)),
                ('qty', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('sold_date', models.DateField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_number', models.CharField(max_length=20)),
                ('customer_payment_ss', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('mail_sent', models.BooleanField(default=False)),
                ('ticket_sent_codes', models.CharField(max_length=255)),
            ],
        ),
    ]
