# Generated by Django 5.1 on 2025-03-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_alter_ticket_customer_payment_ss'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event_id',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_sent_codes',
            field=models.CharField(default='', max_length=255),
        ),
    ]
