# Generated by Django 5.1 on 2025-03-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0003_ticket_event_id_alter_ticket_ticket_sent_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seller_id',
            field=models.CharField(max_length=12),
        ),
    ]
