# Generated by Django 5.1 on 2025-03-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_alter_ticket_seller_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
