# Generated by Django 5.1 on 2025-03-08 06:31

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0005_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=10, unique=True)),
                ('event_id', models.CharField(max_length=10)),
                ('event_date_id', models.CharField(max_length=10)),
                ('seller_id', models.CharField(max_length=12)),
                ('qty', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('sold_date', models.DateField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_number', models.CharField(max_length=20)),
                ('customer_payment_ss', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='screen_shots/')),
                ('approved', models.BooleanField(default=False)),
                ('mail_sent', models.BooleanField(default=False)),
                ('ticket_sent_codes', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
