# Generated by Django 5.1 on 2025-03-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0006_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedticket',
            name='reseller_id',
            field=models.CharField(max_length=12),
        ),
    ]
