# Generated by Django 5.1 on 2025-03-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0007_alter_assignedticket_reseller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
    ]
