# Generated by Django 5.1 on 2025-06-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0008_ticket_scanned'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_qty', models.CharField(max_length=10)),
                ('ticket_price', models.CharField(max_length=10)),
                ('reseller_id', models.CharField(max_length=12)),
                ('event_date_id', models.CharField(max_length=10)),
                ('assigned_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
