# Generated by Django 5.1 on 2025-06-14 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0010_ticket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtickethistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
