# Generated by Django 5.1 on 2025-06-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0011_assignedtickethistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_sent_codes',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
