# Generated by Django 5.1 on 2025-09-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0012_alter_ticket_ticket_sent_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
