# Generated by Django 5.1 on 2025-07-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0004_user_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rented_event_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
