# Generated by Django 5.1 on 2025-03-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_images',
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='event_date_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
