# Generated by Django 5.1 on 2025-03-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_remove_event_event_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='s3_bucket_folder',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
