# Generated by Django 5.1 on 2025-03-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_event_city_event_event_address_event_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdate',
            name='total_number_of_tickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='number_of_tickets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
