# Generated by Django 5.1 on 2025-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_eventdate_total_number_of_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='total_number_of_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
