# Generated by Django 5.1 on 2025-04-22 08:35

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_alter_eventdate_total_number_of_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_banner',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='event_banners/'),
        ),
    ]
