# Generated by Django 5.1 on 2025-04-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0007_event_event_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_free_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_payment_ss_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_qty_predetermined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_rented_evnet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='predetermined_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
