# Generated by Django 5.1 on 2025-04-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0008_event_is_free_event_event_is_payment_ss_needed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_rented_evnet',
            new_name='is_rented_event',
        ),
    ]
