# Generated by Django 5.1 on 2025-04-22 19:48

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0009_rename_is_rented_evnet_event_is_rented_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_pass',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='event_banners/'),
        ),
        migrations.AddField(
            model_name='event',
            name='pass_qr_dimension',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
