# Generated by Django 5.1 on 2025-07-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0011_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_pass',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
