# Generated by Django 5.1 on 2025-07-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0012_event_max_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
