# Generated by Django 5.1 on 2025-07-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0013_alter_event_event_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pass_qr_dimension',
            field=models.CharField(blank=True, default='151, 151 | 1775, 240 | 170, 120', max_length=255, null=True),
        ),
    ]
